FROM node:14-alpine

RUN apk update

ENV NODE_HEAPDUMP_OPTIONS nosignal

WORKDIR "/app"

# Install nodemon for use with "dev" mode
RUN npm install -g nodemon

# Bundle app source and install dependencies
COPY . /app

RUN npm install

USER node

CMD ["/bin/bash"]